### ISSUE TITLE
Jobs aren't automatically started

### ISSUE THREAD

**Issue by ahme-d** [barryvdh/laravel-async-queue#25]
On using Queue::Push() jobs are inserted in the database with status 0 and not started. 
On using something like : php artisan queue:async 5 
It works perfectly.

Tested on Windows/Debian 7/OSX

**Comment by Slipy90** [comment]
Hi!

I think I found the solution for windows users.
There was two problems around `exec()`:

1. Wrong start parametering. The first param with double quotes is the title of the window and after that comes the program and so on. Because you use `escapeshellarg()` the command was the following:
`start /B "php" artisan queue:async 72 --env=local > NUL`, so php is the name of the new window and artisan was the program to start. Put two double quotes after the /B param in `getBackgroundCommand()` and the command will be:
`start /B "" "php" artisan queue:async 72 --env=local > NUL`
2. I don't know why but the `exec()` method always run synchronously. For this I found the solution here: http://php.net/manual/en/function.exec.php#86329

After these fixies it works like a charm for me.

Thanks for this plug-in :)

**Comment by barryvdh** [comment]
@Slipy90 On what branch are you? The master branch doesn't escape the php command on windows and uses the Symfony Process instead of exec.

**Comment by barryvdh** [comment]
I've tagged `v0.3.1`, can you try with that?

**Comment by Slipy90** [comment]
I used `v0.3.0` and updated to `v0.3.1` and works like a charm! Thanks for it!
